class CategoryCode

def self.all

end


BUILDING_PERMIT_CATEGORIES = {
01: "GENERAL BUILDING—COMMERCIAL",
02: "SUB—GENERAL BUILDING—RESIDENTIAL",
08: "CANVAS AWNING",
10: "COMMUNICATION TOWER 15 DEMOLITION",
18: "FENCE",
19: "FLAGPOLE—SATELLITE DISH",
22: "GARAGE DOOR REPLACEMENT",
29: "METAL AWNING & STORM SHUTTER 35 ORNAMENTAL IRON",
48: "SCREEN ENCLOSURES",
51: "SIGN (NON-ELECTRIC)",
55: "SWIMMING POOL",
82: "WINDOWS (RESIDENTIAL OR COMMERCIAL)",
83: "STORE FRONT (RESIDENTIAL OR COMMERCIAL)",
84: "GLAZED CURTAIN WALLS",
86: "TRAILER TIE DOWN 88 WALK-IN COOLER",
91: "MARINAS",
92: "LOW SLOPE APPLICATIONS (GRAVEL, SMOOTH MODIFIED, SINGLE PLY)",
95: "SHINGLES (ASPHALT, FIBERGLASS)",
96: "SHINGLES (METAL ROOFS/WOOD SHINGLES & SHAKE)",
99: "SOIL IMPROVEMENT",
0100: "BULK STORAGE PROPANE TANK",
0101: "REMOVABLE STORM PANELS",
0102: "TIE DOWN OF STORAGE CONTAINERS/MISCELLANEOUS ITEMS",
0104: "SINGLE ENTRANCE DOOR",
0106: "LIGHTWEIGHT CONCRETE",
0107: "TILE ROOF",
0109: "WATERPROOFING SYSTEMS",
0113: "CHINESE DRYWALL REPAIR – RESIDENTIAL",
0114: "CHINESE DRYWALL REPAIR – COMMERCIAL"
}

end