class Category

  def self.all
    {
      "Commercial / Office"               => COMMERCIAL_OFFICE,
      "Residential"                       => RESIDENTIAL,
      "Leisure / Travel / Recreational"   => LEISURE_TRAVEL_RECREATIONAL,
      "Retail / Services"                 => RETAIL_SERVICES,
      "Medical"                           => MEDICAL,
      "Education"                         => EDUCATION,
      "Miscellaneous"                     => MISCELLANEOUS
    }
  end

  # Commercial / Offices categories
  COMMERCIAL_OFFICE = ["OFFICE USE ONLY",
    "OFFICE - PROFESSIONAL BUILDINGS",
    "OFFICE - SALES",
    "ENTR/FEAT-GATEHOUSE/WATCHMAN TRAILER"
  ]

  # Residential categories
  RESIDENTIAL = ["SINGLE FAM RES-CLUST-ZERO LOT-TOWN HOUSE",
    "5 UNITS OR MORE  - RESIDENTIAL", "DUPLEX",
    "APT BUILDING 3-4 UNITS",
    "TRAILER TIE DOWNS"
  ]
  # Leisure / Travel / Recreational categories
  LEISURE_TRAVEL_RECREATIONAL = [ "BAR-LOUNGE-NIGHT CLUB",
    "RESTAURANT/CAFET/BAR/LOUNGE/NIGHT CLUB",
    "BAR/COCKTAIL LOUNGE/RESTAURANTS",
    "RECREATIONAL COURTS - CLUB HOUSE",
    "CABANA/CHICKEE/GAZEBO/CLUB HOUSE/REC BDG",
    "SHORT TERM EVENT",
    "RESTAURANT-CAFETERIA",
    "HOTEL",
    "MOTEL",
    "GYM/EXERCISE CLUB",
    "BOWLING ALLEY/SKATING RINK"
  ]

  # Retail / Services categories
  RETAIL_SERVICES = ["RETAIL SALES",
    "BEAUTY SALON-BARBER SHOP",
    "GAS/SERV STATION/AUTO REPAIR/CAR WASH",
    "CAR DEALERSHIP - NEW",
    "CAR DEALERSHIP - USE",
    "PARKING GARAGE/OPEN DECK",
    "BODY AND MECHANICAL REPAIR SHOPS-VEHICLS",
    "BANKS - AUTOMATIC TELLER",
    "FUNERAL HOME",
    "BANQUET HALL",
    "WAREHOUSE",
    "WAREHOUSE/STORAGE"
  ]

  # Medical categories
  MEDICAL = ["HOSPITALS",
    "ANIMAL HOSPITAL",
    "CLINIC/SANITARIUMS/HEALTH CENTERS",
    "RESEARCH CENTER - LABORATORY",
    "REST HOMES/CONVALES/ACLF/ORPHANAGE"
  ]

  # Education categories
  EDUCATION = ["DAYCARE - KINDERGARTEN",
    "TRADE SCHOOLS",
    "SCHOOL BUILDINGS",
    "COLLEGE - UNIVERSITY",
    "LIBRARIES - MUSEUMS - SCIENCE - ZOO"
  ]

  # Industrial categories
  INDUSTRIAL = ["INDUSTRIAL USES",
    "AIRPORT-SEAPORT - TRUCK TERMINALS",
    "CONSTRUCTION TRAILER/HANDICAPPED RAMP",
    "MARINA",
    "BAKERY PLANT",
    "PAVING/OPEN LOTS",
    "MANUFACTURING",
    "AGRICULTURAL",
    "UTILITIES"
  ]

  # Miscellaneous categories
  MISCELLANEOUS = ["GOVERNMENT FACILITIES",
    "CEMENTARY",
    "CHURCHES-RELIGIOUS BUILDINGS",
    "JAIL/STOCKADE"
  ]


end